install_github("briatte/ggnet")
install_github("adw96/breakaway")
install_github("cboettig/knitcitations")
# install_github("cttobin/ggthemr")
install_github("christophergandrud/networkD3")
install_github('decisionpatterns/tidyimpute')
install_github("earlywarningtoolbox/earlywarnings-R/earlywarnings")
install_github("GuillemSalazar/EcolUtils")
install_github('edwindj/whisker')
install_github("ggobi/GGally")
install_github("hadley/pkgdown")
# install_github("hoesler/rwantshue")
install_github("joey711/phyloseq")
install_github("kalimu/genderizeR")
#install_github("microbiome/HITChipDB")
install_github("microbiome/microbiome")
install_github("microbiome/RPA")
install_github('ramnathv/rCharts')
install_github('ramnathv/slidify')
install_github('ramnathv/slidifyLibraries')
# install_github("reptalex/phylofactor")
#install_github("ropengov/gisfin")
install_github("ropengov/pxweb")
install_github("ropensci/gender")
# install_github("ropensci/genderdata")
install_github('rstudio/markdown')
install_github("rstudio/rmarkdown")
install_github('rstudio/shiny')
install_github("thomasp85/patchwork")
install_github("twbattaglia/MicrobeDS")
install_github("wch/webshot")
install_github("zdk123/SpiecEasi")
install_github("FelixErnst/SEtup")