#source('http://www.bioconductor.org/biocLite.R')
#update.packages()
#biocLite()

# install.packages("BiocManager")
install.packages("devtools"); 
library(devtools)

install.packages("BiocManager"); 
library(BiocManager)

BiocManager::install("affy", suppressUpdates = FALSE)
BiocManager::install("ape", suppressUpdates = FALSE) # circular hclust dendrograms etc
BiocManager::install("Biobase", suppressUpdates = FALSE)
BiocManager::install("BiocCheck", suppressUpdates = FALSE)
BiocManager::install("BiocStyle", suppressUpdates = FALSE)
# Requires installing curl and setting curl-config path
# see locate libcurl and locate curl-config and
# http://www.omegahat.org/RCurl/FAQ.html
#~/local/bin/curl-7.20.1> ./configure --prefix=/users/lmlahti/bin
# make && make install
# After adding path to  .cshrc
#(line: set path=($path /home/lmlahti/bin/curl-7.21.3)
# and "source .cshrc"
# and isntalling "libcurl-ocaml-dev" with synaptic
#I got RCurl installed with:
#~/local/R/R-2.12.0/bin/R CMD INSTALL ~/local/R/packages/RCurl_1.5-0.tar.gz
BiocManager::install("biomaRt", suppressUpdates = FALSE)# Requires RCurl
BiocManager::install("cMAP", suppressUpdates = FALSE)
BiocManager::install("dada2", suppressUpdates = FALSE) 
BiocManager::install("DBI", suppressUpdates = FALSE) #RMySQL is a dependency?, AnnBuilder
BiocManager::install("DESeq2", suppressUpdates = FALSE)
BiocManager::install("df2json", suppressUpdates = FALSE)
BiocManager::install("DirichletMultinomial", suppressUpdates = FALSE) # DMMs; may require libgsl0-dev
# BiocManager::install("DPpackage", suppressUpdates = FALSE) # Dirichlet Processes / topic models et
BiocManager::install("EMDomics", suppressUpdates = FALSE)
BiocManager::install("FD", suppressUpdates = FALSE)
BiocManager::install("genefilter", suppressUpdates = FALSE)
BiocManager::install("ggbio", suppressUpdates = FALSE)
BiocManager::install("ggiraph", suppressUpdates = FALSE)
BiocManager::install("glmnet", suppressUpdates = FALSE) # Lasso, elastic net, regularized generalized linear models
BiocManager::install("GO.db", suppressUpdates = FALSE)
BiocManager::install("graph", suppressUpdates = FALSE)
BiocManager::install("impute", suppressUpdates = FALSE)
BiocManager::install("kohonen", suppressUpdates = FALSE) # better than 'som' package
BiocManager::install("limma", suppressUpdates = FALSE)
BiocManager::install("MASS", suppressUpdates = FALSE)
BiocManager::install("M3C")
BiocManager::install("Matrix", suppressUpdates = FALSE) # boosting matrix calculations
BiocManager::install("minet", suppressUpdates = FALSE)
BiocManager::install("NCIgraph", suppressUpdates = FALSE)
BiocManager::install("nlme", suppressUpdates = FALSE)
BiocManager::install("oligo", suppressUpdates = FALSE)
BiocManager::install("outliers", suppressUpdates = FALSE)
BiocManager::install("pamr", suppressUpdates = FALSE)
BiocManager::install("phyloseq", suppressUpdates = FALSE)
BiocManager::install("preprocessCore", suppressUpdates = FALSE)
BiocManager::install("qvalue", suppressUpdates = FALSE)
BiocManager::install("R2HTML", suppressUpdates = FALSE)
BiocManager::install("RbcBook1", suppressUpdates = FALSE)
BiocManager::install("RColorBrewer", suppressUpdates = FALSE)
BiocManager::install("Rgraphviz", suppressUpdates = FALSE) # graphviz and its dependencies
BiocManager::install("RSQLite", suppressUpdates = FALSE)
BiocManager::install("RSVGTipsDevice", suppressUpdates = FALSE) 
BiocManager::install("sva", suppressUpdates = FALSE)
BiocManager::install("svDialogs", suppressUpdates = FALSE)
BiocManager::install("tikzDevice", suppressUpdates = FALSE)
BiocManager::install("vegan", suppressUpdates = FALSE)
BiocManager::install("WGCNA", suppressUpdates = FALSE)
BiocManager::install("XML", suppressUpdates = FALSE) # libxml2-dev, xml2 with synaptic

BiocManager::install("antagomir/netresponse")
install_github("briatte/ggnet")
install_github("cboettig/knitcitations")
install_github("cttobin/ggthemr")
install_github("christophergandrud/networkD3")
install_github("earlywarningtoolbox/earlywarnings-R/earlywarnings")
install_github('edwindj/whisker')
install_github("ggobi/GGally")
install_github("hadley/pkgdown")
# install_github("hoesler/rwantshue")
install_github("joey711/phyloseq")
install_github("kalimu/genderizeR")
#install_github("microbiome/HITChipDB")
install_github("microbiome/microbiome")
install_github("microbiome/RPA")
install_github('ramnathv/rCharts')
install_github('ramnathv/slidify')
install_github('ramnathv/slidifyLibraries')
# install_github("reptalex/phylofactor")
#install_github("ropengov/gisfin")
install_github("ropengov/pxweb")
install_github("ropensci/gender")
# install_github("ropensci/genderdata")
install_github('rstudio/markdown')
install_github("rstudio/rmarkdown")
install_github('rstudio/shiny')
install_github("thomasp85/patchwork")
install_github("twbattaglia/MicrobeDS")
install_github("wch/webshot")
install_github("zdk123/SpiecEasi")

install.packages("abind")
install.packages("ade4")
install.packages("akima")
install.packages("animation") 
install.packages("babynames")
install.packages("bayesm")
install.packages("ber")
install.packages("bookdown")
install.packages("brew")
install.packages("cacheSweave")
install.packages("Cairo")
install.packages("caper")
install.packages("captioner")
install.packages(c("gender", "genderdata"), repos = "http://packages.ropensci.org", type = "source")
install.packages("classInt")
install.packages("compositions")
install.packages("countrycode")
install.packages("covr")
install.packages("cowplot")
install.packages("data.table")
install.packages("DataCombine")
install.packages("deSolve")
install.packages("diptest")
install.packages("dlstats")
install.packages("dmt")
install.packages("doMC")
install.packages("downloader")
install.packages("dplyr")
install.packages("DT")
install.packages("dygraphs")
install.packages("e1071") # SVM and many other machine learning tools
install.packages("ellipse")
install.packages("energy")
install.packages("entropy")
install.packages("fastcluster")
install.packages("fastICA")
install.packages("FGN")
install.packages("fields")
install.packages("flexdashboard")
install.packages("flexmix")
install.packages("fNonlinear")
install.packages("foreach")
install.packages("formatR")
install.packages("fpc") # Prediction strength
install.packages("fractal")
install.packages("fractaldim")
install.packages("FSA")
install.packages("funModeling")
install.packages("gcookbook")
install.packages("gdata")
install.packages("geigen")
install.packages("geofacet")
install.packages("gender")
install.packages("getopt")
install.packages("ggbeeswarm")
install.packages("ggigraph")
install.packages("ggm")
install.packages("ggmap")
install.packages("ggplot2")
install.packages("ggpmisc")
install.packages("ggspectra")
install.packages("ggpubr")
install.packages("ggrepel")
install.packages("ggROC")
install.packages("ggthemes")
install.packages("gghighlight")
install.packages("ggfortify")
install.packages('googleVis')
install.packages("googleViz")
install.packages("GPArotation")
install.packages("gpclib")
install.packages("gplots")
install.packages("gridExtra")
install.packages("GUniFrac")
install.packages("highcharter")
install.packages('highlight')
install.packages("hrbrthemes")
install.packages("httpcache")
install.packages("httptest")
install.packages("httr")
install.packages("ifultools")
install.packages("igraph", suppressUpdates = FALSE) #see http://cneurocvs.rmki.kfki.hu/igraph/download.html
install.packages('inline')
install.packages("intergraph")
install.packages("janitor")
install.packages("Kendall")
install.packages("knitcitations")
install.packages("knitr")
install.packages("lawstat")
install.packages("leaflet")
install.packages("lme4")
install.packages("magrittr")
install.packages('mapproj')
install.packages("maps")
install.packages("maptools")
install.packages("mclust") # Gaussian mixture EM and other useful stuff
install.packages("MCMCpack")
install.packages("memisc")
install.packages("mitools")
install.packages("mixOmics")
install.packages("mixtools")
install.packages("moments")
install.packages("multcomp")
install.packages("mvnormtest")
install.packages("mvtnorm") #contains rmvnorm for multivariate normal sampling
install.packages("netdiffuseR")
install.packages("network")
install.packages("NMF")
library(NMF); install.extras("NMF")
install.packages("nortest")
install.packages("nws")
install.packages("openxlsx")
install.packages("outliers")
install.packages("ows4R")
install.packages("packfor", repos="http://R-Forge.R-project.org")
install.packages('pbdZMQ') 
install.packages("PerformanceAnalytics")
install.packages("permute")
install.packages("phytools")
install.packages("picante")
install.packages("pkgmaker") 
install.packages("plotly")
install.packages("plotrix")
install.packages("plotROC")
install.packages("pracma")
install.packages("prettydoc")
install.packages("pROC")
install.packages('psych') # factor analysis with BIC & RMSEA
install.packages("pxR")
install.packages("qdap")
install.packages("qpdf")
install.packages("quadprog")
install.packages("quantmod")
install.packages("randomForest")
install.packages("raster")
install.packages('Rcpp')
install.packages("rcrossref")
install.packages("Rd2roxygen")
install.packages("rdryad")
install.packages("readODS")
install.packages("readr")
install.packages("readxl")
install.packages("relaimpo")
install.packages("reldist")
install.packages('repr') 
install.packages("reshape2")
install.packages("rgdal")
install.packages("rgeos") # install GEOS first from http://trac.osgeo.org/geos/
install.packages("rgexf")
install.packages("rgl")
install.packages("rhub")
install.packages("rjstat")
install.packages("RgoogleMaps")
install.packages("rio")
install.packages("rJava")
install.packages("rjson")
install.packages("rmarkdown")
install.packages("rmdformats")
install.packages("RMySQL") # system("wget http://cran.r-project.org/src/contrib/RMySQL_0.9-3.tar.gz")
install.packages("robCompositions")
install.packages("robustbase")
install.packages("RODBC")
install.packages("roxygen2")
install.packages("rsdmx")
install.packages('rstan', type = 'source')
install.packages('rstanarm')
install.packages("Rtsne")
install.packages("RUnit")
install.packages("R.utils")
install.packages("rvest")
install.packages("rvg")
install.packages("Rwave")
install.packages("rworldmap")
install.packages("rworldxtra")
install.packages("sapa")
install.packages("scatterplot3d")
install.packages('sde')
install.packages('sf')
install.packages('shiny')
install.packages('skimr')
install.packages("sna")
install.packages("som")
install.packages("sorvi")
install.packages("sp")
install.packages("spdep")
install.packages("spelling")
install.packages("splus2R")
install.packages("stinepack")
install.packages("stringdist")
install.packages("stringi")
install.packages("stringr")
install.packages("structSSI")
install.packages("summarytools")
install.packages("survey")
install.packages("synchronicity")
install.packages("tau")
install.packages("tensorA")
install.packages("testthat")
install.packages("tgp")
install.packages("theseus")
install.packages("tibble")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("tm")
install.packages("tmap")
install.packages("tmaptools")
install.packages("tricolore")
install.packages("tseries")
install.packages("tsne")
install.packages('tuneR')
install.packages("umap")
install.packages("units")
install.packages("untb")
install.packages("vars")
install.packages("vegan")
install.packages('VGAM')
install.packages("viridis")
install.packages("Voss")
install.packages("WDI")
install.packages("wesanderson")
install.packages("WGCNA")
#install.packages("wfs4R")
install.packages("wmtsa")
install.packages("wordcloud")
install.packages("XLConnect")
install.packages("xlsx")
install.packages("xlsxjars")
install.packages("xtable")

install.packages("extrafont")
library(extrafont); font_import()
options(repos = c(getOption("repos"), rstan = "http://wiki.rstan-repo.googlecode.com/git/"))
