install_github('ramnathv/rCharts')
install_github('ramnathv/slidify')
install_github('ramnathv/slidifyLibraries')
# install_github("reptalex/phylofactor")
install_github("ropengov/pxweb")
#install_github("ropensci/gender")
install_github('rstudio/markdown')
install_github("rstudio/rmarkdown")
# install_github('rstudio/shiny')
install_github("thomasp85/patchwork")
install_github("twbattaglia/MicrobeDS")
install_github("wch/webshot")
install_github("zdk123/SpiecEasi")
install_github("FelixErnst/SEtup")
