install.packages("nortest")
install.packages("nws")
install.packages("openxlsx")
install.packages("outliers")
install.packages("ows4R")
install.packages("packfor", repos="http://R-Forge.R-project.org")
install.packages('pbdZMQ') 
install.packages("PerformanceAnalytics")
install.packages("permute")
install.packages("pgirmess")
install.packages("phangorn")
install.packages("pheatmap")
install.packages("philentropy")
install.packages("phytools")
install.packages("picante")
# install.packages("pkgmaker")
install.packages("pkgdown") 
install.packages("plotly")
install.packages("plotrix")
install.packages("plotROC")
install.packages("PMCMR")
install.packages("poweRlaw")
install.packages("pracma")
install.packages("prettydoc")
install.packages("pROC")
install.packages('psych') # factor analysis with BIC & RMSEA
install.packages("pxR")
install.packages("qdap")
install.packages("qpdf")
install.packages("quadprog")
install.packages("quantmod")
install.packages("randomForest")
install.packages("randomA")
install.packages("raster")
install.packages('Rcpp')
install.packages("rcrossref")
install.packages("Rd2roxygen")
install.packages("rdryad")
install.packages("readODS")
install.packages("readr")
install.packages("readxl")
install.packages("relaimpo")
install.packages("reldist")
# install.packages('remotes')
install.packages('repr') 
install.packages("reshape2")
install.packages("rgdal")
install.packages("rgeos") # install GEOS first from http://trac.osgeo.org/geos/
install.packages("rgexf")
install.packages("rgl")
install.packages("rhub")
install.packages("rjstat")
install.packages("RgoogleMaps")
install.packages("rio")
install.packages("rJava")
install.packages("rjson")
install.packages("rmarkdown")
install.packages("rmdformats")
install.packages("RMySQL") # system("wget http://cran.r-project.org/src/contrib/RMySQL_0.9-3.tar.gz")
install.packages("robCompositions")
install.packages("robustbase")
install.packages("RODBC")
install.packages("roxygen2")
install.packages("rsdmx")
install.packages('rstan', type = 'source')
install.packages('rstanarm')
install.packages("Rtsne")
install.packages("RUnit")
install.packages("R.utils")
install.packages("rvest")
install.packages("rvg")
install.packages("Rwave")
# install.packages("rworldmap")
# install.packages("rworldxtra")
install.packages("sapa")
install.packages("scatterplot3d")
install.packages('sde')
install.packages('sf')
install.packages('shiny')
install.packages("sjPlot")
install.packages('skimr')
install.packages("sna")
install.packages("som")
install.packages("sorvi")
install.packages("sp")
install.packages("spdep")
install.packages("spelling")
install.packages("splus2R")
install.packages("stinepack")
install.packages("stringdist")
install.packages("stringi")
install.packages("stringr")
install.packages("structSSI")
install.packages("summarytools")
install.packages("survey")
install.packages("synchronicity")
install.packages("tau")
install.packages("tensorA")
install.packages("testthat")
install.packages("trackdown")
install.packages("tgp")
install.packages("theseus")
install.packages("tibble")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("tm")
install.packages("tmap")
install.packages("tmaptools")
install.packages("tricolore")
install.packages("tseries")
install.packages("tsne")
install.packages('tuneR')
install.packages("umap")
install.packages("uwot")
install.packages("units")
install.packages("untb")
install.packages("usethis")
install.packages("vars")
install.packages("vegan")
install.packages('VGAM')
install.packages('VIM')
install.packages("viridis")
install.packages("Voss")
install.packages("WDI")
install.packages("wesanderson")
install.packages("WGCNA")
#install.packages("wfs4R")
install.packages("wmtsa")
install.packages("wordcloud")
install.packages("XLConnect")
# install.packages("xlsx")
install.packages("xlsxjars")
install.packages("xtable")
install.packages("quarto")

install.packages("extrafont")
library(extrafont); font_import()
options(repos = c(getOption("repos"), rstan = "http://wiki.rstan-repo.googlecode.com/git/"))
install_github('ramnathv/rCharts')
install_github('ramnathv/slidify')
install_github('ramnathv/slidifyLibraries')
# install_github("reptalex/phylofactor")
install_github("ropengov/pxweb")
#install_github("ropensci/gender")
install_github('rstudio/markdown')
install_github("rstudio/rmarkdown")
# install_github('rstudio/shiny')
install_github("thomasp85/patchwork")
install_github("twbattaglia/MicrobeDS")
install_github("wch/webshot")
install_github("zdk123/SpiecEasi")
install_github("FelixErnst/SEtup")
