df$abundance <- abundances(x)[cm[[1]],]
p <- ggplot(df,
         aes(x = days_since_experiment_start, y = abundance)) +
       geom_smooth() +
       geom_point()

print(p)install_github('rstudio/shiny')
install_github("wch/webshot")
install_github("zdk123/SpiecEasi")

install.packages("abind")
install.packages("ade4")
install.packages("akima")
install.packages("animation") 
install.packages("babynames")
install.packages("bayesm")
install.packages("ber")
install.packages("bookdown")
install.packages("brew")
install.packages("cacheSweave")
install.packages("Cairo")
install.packages("caper")
install.packages("captioner")
install.packages(c("gender", "genderdata"), repos = "http://packages.ropensci.org", type = "source")
install.packages("classInt")
install.packages("compositions")
install.packages("countrycode")
install.packages("cowplot")
install.packages("data.table")
install.packages("DataCombine")
install.packages("deSolve")
install.packages("diptest")
install.packages("dlstats")
install.packages("dmt")
install.packages("doMC")
install.packages("downloader")
install.packages("dplyr")
install.packages("DT")
install.packages("dygraphs")
install.packages("e1071") # SVM and many other machine learning tools
install.packages("ellipse")
install.packages("energy")
install.packages("entropy")


install.packages("fastcluster")
install.packages("fastICA")
install.packages("FGN")
install.packages("fields")
install.packages("flexdashboard")
install.packages("flexmix")
install.packages("fNonlinear")
install.packages("foreach")
install.packages("formatR")
install.packages("fpc") # Prediction strength
install.packages("fractal")
install.packages("fractaldim")
install.packages("FSA")
install.packages("funModeling")
install.packages("gcookbook")
install.packages("gdata")
install.packages("geigen")
install.packages("gender")
install.packages("getopt")
install.packages("ggigraph")
install.packages("ggm")
install.packages("ggmap")
install.packages("ggplot2")
install.packages("ggpmisc")
install.packages("ggspectra")
install.packages("ggpubr")
install.packages("ggrepel")
install.packages("ggROC")
install.packages("ggthemes")
install.packages("gghighlight")
install.packages("ggfortify")
install.packages('googleVis')
install.packages("googleViz")
install.packages("GPArotation")
install.packages("gpclib")
install.packages("gplots")
install.packages("gridExtra")
install.packages("GUniFrac")
install.packages("highcharter")
install.packages('highlight')
install.packages("hrbrthemes")
install.packages("http://prof.beuth-hochschule.de/fileadmin/user/groemping/downloads/relaimpo_2.2-2.tar.gz", type = "source")
install.packages("httr")
install.packages("ifultools")
install.packages("igraph", suppressUpdates = FALSE) #see http://cneurocvs.rmki.kfki.hu/igraph/download.html
install.packages('inline')
install.packages("intergraph")
install.packages("Kendall")
install.packages("knitcitations")
install.packages("knitr")
install.packages("lawstat")
install.packages("leaflet")
install.packages("lme4")
install.packages("magrittr")
install.packages('mapproj')
install.packages("maps")
install.packages("maptools")
install.packages("mclust") # Gaussian mixture EM and other useful stuff
install.packages("MCMCpack")
install.packages("memisc")
install.packages("mitools")
install.packages("mixOmics")
install.packages("mixtools")
install.packages("moments")
install.packages("multcomp")
install.packages("mvnormtest")
install.packages("mvtnorm") #contains rmvnorm for multivariate normal sampling
install.packages("netdiffuseR")
install.packages("network")
install.packages("nortest")
install.packages("nws")
install.packages("openxlsx")
install.packages("outliers")
install.packages("packfor", repos="http://R-Forge.R-project.org")
install.packages('pbdZMQ') 
install.packages("PerformanceAnalytics")
install.packages("permute")
install.packages("phytools")
install.packages("plotly")
install.packages("plotrix")
install.packages("plotROC")
install.packages("pracma")
install.packages("prettydoc")
install.packages("pROC")
install.packages("psych")
install.packages('psych') # factor analysis with BIC & RMSEA
install.packages("pxR")
install.packages("qdap")
install.packages("quadprog")
install.packages("quantmod")
install.packages("randomForest")
install.packages("raster")
install.packages('Rcpp')
install.packages("rcrossref")
install.packages("Rd2roxygen")
install.packages("rdryad")
install.packages("readODS")
install.packages("readr")
install.packages("readxl")
install.packages("reldist")
install.packages('repr') 
install.packages("reshape2")

# Geographical information
# required installation of 
# geos-dev with synaptic and 
# PROJ.4 from http://trac.osgeo.org/proj/wiki/WikiStart#Download
# in practice through 
# ~/Louhos/takomo/installation/sorvi-install-dependencies-debian.sh
install.packages("rgdal")

install.packages("rgeos") # install GEOS first from http://trac.osgeo.org/geos/
install.packages("rgl")
install.packages("RgoogleMaps")
install.packages("rio")
install.packages("rJava")
install.packages("rjson")
install.packages("rmarkdown")
install.packages("rmdformats")
install.packages("RMySQL") # system("wget http://cran.r-project.org/src/contrib/RMySQL_0.9-3.tar.gz")
install.packages("robCompositions")
install.packages("robustbase")
install.packages("RODBC")
install.packages("roxygen2")
install.packages("rsdmx")
install.packages('rstan', type = 'source')
install.packages('rstanarm')
install.packages("Rtsne")
install.packages("RUnit")
install.packages("R.utils")
install.packages("rvest")
install.packages("rvg")
install.packages("Rwave")
install.packages("rworldmap")
install.packages("rworldxtra")
install.packages("sapa")
install.packages("scatterplot3d")
install.packages("scimapClient", repos="http://scisoft-net-map.isri.cmu.edu/static/R")
install.packages('sde')
install.packages('shiny')
install.packages("sna")
install.packages("som")
install.packages("sorvi")
install.packages("sp")
install.packages("spdep")
install.packages("splus2R")
install.packages("stinepack")
install.packages("stringdist")
install.packages("stringr")
install.packages("structSSI")
install.packages("survey")
install.packages("synchronicity")
install.packages("tau")
install.packages("tensorA")
install.packages("testthat")
install.packages("tgp")
install.packages("theseus")
install.packages("tibble")
install.packages("tidyr")
install.packages("tidyverse")
install.packages("tm")
install.packages("tmap")
install.packages("tmaptools")
install.packages("tseries")
install.packages("tsne")
install.packages('tuneR')
install.packages("untb")
install.packages("vars")
install.packages("vegan")
install.packages('VGAM')
install.packages("viridis")
install.packages("Voss")
install.packages("WDI")
install.packages("wesanderson")
install.packages("WGCNA")
install.packages("wmtsa")
install.packages("wordcloud")
install.packages("XLConnect")
install.packages("xlsx")
install.packages("xlsxjars")
install.packages("xtable")

install.packages("extrafont")
library(extrafont); font_import()
options(repos = c(getOption("repos"), rstan = "http://wiki.rstan-repo.googlecode.com/git/"))

install.packages("pkgmaker") 
install.packages("NMF") 
library(NMF); install.extras("NMF")

# biocUpgrade()

